//Auth Manager
export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const USER_AUTH_ERROR = "USER_AUTH_ERROR";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";

//Menu
export const GET_OWNED_MENU = "GET_OWNED_MENU";
export const GET_OWNED_MENUS = "GET_OWNED_MENUS";
export const DELETE_OWNED_MENU = "DELETE_OWNED_MENU";
export const UPDATE_OWNED_MENU = "UPDATE_OWNED_MENU";
export const CREATE_OWNED_MENU = "CREATE_OWNED_MENU";
export const OWNED_MENU_ERROR = "OWNED_MENU_ERROR";

//Order
export const GET_OWNED_ORDER = "GET_OWNED_ORDER";
export const GET_OWNED_ORDERS = "GET_OWNED_ORDERS";
export const DELETE_OWNED_ORDER = "DELETE_OWNED_ORDER";
export const UPDATE_OWNED_ORDER = "UPDATE_OWNED_ORDER";
export const CREATE_OWNED_ORDER = "CREATE_OWNED_ORDER";
export const OWNED_ORDER_ERROR = "OWNED_ORDER_ERROR";
export const CREATE_CLIENT_ORDER = "CREATE_CLIENT_ORDER";
export const ADD_TO_CLIENT_ORDER = "ADD_TO_CLIENT_ORDER";
export const CHECKOUT_OWNED_ORDER = "CHECKOUT_OWNED_ORDER";
export const GET_MANAGER_ORDER = "GET_MANAGER_ORDER"
export const GET_MANAGER_ORDERS = "GET_MANAGER_ORDERS"
export const CONFIRM_ORDER = "CONFIRM_ORDER"
export const CANCEL_ORDER = "CANCEL_ORDER"
export const GET_CLIENT_ORDERS = "GET_CLIENT_ORDERS"
//feedback
export const GET_OWNED_FEEDBACK = "GET_OWNED_FEEDBACK";
export const GET_OWNED_FEEDBACKS = "GET_OWNED_FEEDBACKS";
export const DELETE_OWNED_FEEDBACK = "DELETE_OWNED_FEEDBACK";
export const UPDATE_OWNED_FEEDBACK = "UPDATE_OWNED_FEEDBACK";
export const CREATE_OWNED_FEEDBACK = "CREATE_OWNED_FEEDBACK";
export const OWNED_FEEDBACK_ERROR = "OWNED_FEEDBACK_ERROR";

//Restaurant
export const GET_OWNED_RESTAURANT = "GET_OWNED_RESTAURANT";
export const GET_OWNED_RESTAURANTS = "GET_OWNED_RESTAURANTS";
export const DELETE_OWNED_RESTAURANT = "DELETE_OWNED_RESTAURANT";
export const UPDATE_OWNED_RESTAURANT = "UPDATE_OWNED_RESTAURANT";
export const CREATE_OWNED_RESTAURANT = "CREATE_OWNED_RESTAURANT";
export const OWNED_RESTAURANT_ERROR = "OWNED_RESTAURANT_ERROR";

//Address
export const GET_ADDRESS = "GET_ADDRESS";
export const GET_ADDRESSES = "GET_ADDRESSES";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const CREATE_ADDRESS = "CREATE_ADDRESS";
export const ADDRESS_ERROR = "ADDRESS_ERROR";

//Category
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CATEGORY_ERROR = "CATEGORY_ERROR";

//product
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";

//Message 
export const SEND_MESSAGE = "SEND_MESSAGE";
export const MESSAGE_ERROR = "MESSAGE_ERROR";
//Dashboard
export const ORDER_NUMBER = "ORDER_NUMBER";
export const ORDER_CONFIRMATION_NUMBER ="ORDER_CONFIRMATION_NUMBER";
export const DASHBOARD_ERROR = "DASHBOARD_ERROR"