//Auth Manager
export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const USER_AUTH_ERROR = "USER_AUTH_ERROR";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";